version: "3.8"
services:
  my-go-blog:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "/root/wait-for-it.sh mysql:3306 && /root/wait-for-it.sh redis:6379 -- /root/main"
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootroot
      - MYSQL_DB=goblog
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: goblog
#    ports:
#      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
#    ports:
#      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
