version: "3.8"
services:
  my-go-blog:
    image: jmyok007/my-go-blog:v1.3
    command: ["/bin/bash", "-c", "/root/wait-for-it.sh redis:6379 && /root/wait-for-it.sh mysql:3306 -t 60 -- /root/main"]
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
      MYSQL_DB: goblog
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: jmyok007/mysql8:goblog-v1.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: goblog
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
